# Site settings
title: Suus
email: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://suus.github.io" # the base hostname & protocol for your site

collections:
  drawings:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "drawings"
    values:
      layout: "drawing"

markdown: kramdown


exclude: ['vendor',
          'Gemfile',
          'Gemfile.lock']
